[project]
name = "traffic-studies"
version = "0.1.0"
description = "A comprehensive traffic analysis dashboard for Crystal, Minnesota, built with Streamlit."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.1",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "plotly>=6.0.1",
    "seaborn>=0.13.2",
    "streamlit>=1.44.1",
]
